name: 'Auto Tag Dart Versions'
description: 'Automatically create tags when you update your pubspec.yaml version'
author: 'jpeiffer'
inputs:
  path:
    description: 'Path to the directory containing the pubspec.yaml file to monitor.'
    required: false
    default: .
  token:
    description: 'The GitHub access token to allow file reading and tag creation.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Update dependencies
      shell: bash
      run: |
        set -e

        dart pub global activate -sgit https://github.com/peiffer-innovations/actions-dart-version-autotag
        dart pub global run dart_version_autotag:tag --token ${{ inputs.token }} --path ${{ inputs.path }} --repository ${{ github.repository }}
