name: 'dart_version_autotag'
description: 'A package that to scan the pubspec.yaml file and automatically create or update a tag in git for it.'
version: '2.1.1+13'
homepage: 'https://github.com/peiffer-innovations/actions-dart-version-autotag'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  args: '^2.5.0'
  github: '^9.24.0'
  http: '^1.2.1'
  intl: '^0.19.0'
  logging: '^1.2.0'
  yaml: '^3.1.2'

dev_dependencies: 
  flutter_lints: '^3.0.2'
  test: '^1.25.4'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
